plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'io.domainlifecycles'
version = '1.1'

publishing {
    publications {
        myLibrary(MavenPublication) {
            from components.java
        }
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

ext {
    dlcVersion = "2.5.0"
}

dependencies {
    api "io.domainlifecycles:mirror:${dlcVersion}"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}